---
output: github_document
---

<!-- README.md is generated from README.Rmd. Please edit that file -->

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
  fig.path = "man/figures/README-",
  out.width = "100%"
)
```

# tg

<!-- badges: start -->
<!-- badges: end -->

This package provides an interface to the [tg C library](https://github.com/tidwall/tg) similar
to [sf](https://github.com/r-spatial/sf) and [geos](https://github.com/paleolimbot/geos).

## Installation

You can install the development version of tg like so:

``` r
pak::pkg_install("program--/tg")
```

## Example Usage

Reading geometry from WKT:

```{r wkt_example}
tg::as_tg("POINT(1 1)")
```

Reading geometry from a GeoJSON string:
```{r geojson_example}
gjson <- '
{ "type": "FeatureCollection",
  "features": [
    { "type": "Feature",
      "geometry": {"type": "Point", "coordinates": [102.0, 0.5]},
      "properties": {"prop0": "value0"}
      },
    { "type": "Feature",
      "geometry": {
        "type": "LineString",
        "coordinates": [
          [102.0, 0.0], [103.0, 1.0], [104.0, 0.0], [105.0, 1.0]
          ]
        },
      "properties": {
        "prop0": "value0",
        "prop1": 0.0
        }
      },
    { "type": "Feature",
       "geometry": {
         "type": "Polygon",
         "coordinates": [
           [ [100.0, 0.0], [101.0, 0.0], [101.0, 1.0],
             [100.0, 1.0], [100.0, 0.0] ]
           ]

       },
       "properties": {
         "prop0": "value0",
         "prop1": {"this": "that"}
         }
       }
    ]
  }
'

tg_geometry <- tg::as_tg(gjson)
tg_geometry

# Converting to a TG Collection
collection <- tg::as_tgc(tg_geometry)
collection

# Creating a data.frame
data.frame(x = 1:3, geometry = collection)
```
